### ISSUE TITLE
Endless loop once the ball moves straight vertical.

### ISSUE THREAD

**Issue by NeoHuang** [johngrib/vim-game-code-break#17]
When the ball goes straight up and down, it falls into endless loop. No matter how you move the bar, it keeps going up and down. maybe add some friction on the bar? 😂

**Comment by johngrib** [comment]
The vertical movement ball is an item made to disappear after 10 bumps.
Endless loop is not what I intended... I'll check it out.

(The item is defined in the following file.
[vim-game-code-break/autoload/VimGameCodeBreak/item_bomb.vim](https://github.com/johngrib/vim-game-code-break/blob/master/autoload/VimGameCodeBreak/item_bomb.vim))

**Comment by johngrib** [comment]
Ah, I realized what the problem is. I'll fix it.
Thank you for your report.

**Comment by johngrib** [comment]
Maybe it will be ok now.

**Comment by NeoHuang** [comment]
thanks for fixing it 👍
