### ISSUE TITLE
how to play with multiple balls at the same time?

### ISSUE THREAD

**Issue by luxa-cchen** [johngrib/vim-game-code-break#20]
thanks for your game first,it is really an interesting idea that play in vim.
I noticed that we could play with two balls at the same time .
it maybe more interesting if we could play  with as many as  balls we want at the same time .

**Comment by johngrib** [comment]
I modified it according to your advice. 
Now you can increase the ball limit by changing the setting.
However, the performance and bug possibilities of the game can go up. If possible, I would like to play with a default of 2.

https://github.com/johngrib/vim-game-code-break#setting
