### ISSUE TITLE
VimGameCodeBreak opens in vertical split 

### ISSUE THREAD

**Issue by supersambo** [johngrib/vim-game-code-break#21]
When i start the game it vertically splits my screen, where the game starts in the left pane and the original remains in the right pane. Any idea how to prevent it from doing this?

**Comment by blueyed** [comment]
Do you want it to not split, but use the current window?

**Comment by supersambo** [comment]
Yes I do not want it to split but play in the current window, as it is demonstrated in the readmes gif.

**Comment by johngrib** [comment]
https://www.reddit.com/r/vim/comments/6l5s9x/blockbreaking_game_in_vim_80/dk9s5ux/

Initially, I designed the game to use the entire screen. However, since most of the source code is on the left side, the game gets bored easily. So I fixed it to 80 cols of screens.
