### ISSUE TITLE
:VimGameCodeBreak opens new vertical split window

### ISSUE THREAD

**Issue by Felixoid** [johngrib/vim-game-code-break#22]
Hi!
By running :VimGameCodeBreak second split window opening instead the same bufer

I tried clean vim environment by commenting in .vimrc all except
```
call plug#begin()
Plug 'johngrib/vim-game-code-break'
call plug#end()
```
My installed version is:
```
pacman -Q | grep vim
gvim 8.0.1476-1
vim-runtime 8.0.1476-1
vim-spell-ru 20150901-1
```
The behavior is same in vim and gvim
![screen_2018-02-22_17-53-41_window](https://user-images.githubusercontent.com/3025537/36552607-8bf1412c-17fa-11e8-9ef3-33aff7c539ba.png)
![screen_2018-02-22_18-09-02_window](https://user-images.githubusercontent.com/3025537/36553040-a02366b0-17fb-11e8-8509-4ab806e23efd.png)

**Comment by johngrib** [comment]
(Translated from Korean to English via a Google Translator.)

Hello. Thank you for playing this game.
It is not a bug that a new vertical window opens when you start a new game.
It is to preserve the original file. (Many people worried that this game might change the original file.)
And the width of the new vertical window is the size I decided to test for months of fun for the game.
I hope you have a satisfactory answer.

**Comment by gnumoksha** [comment]
@johngrib the screen shot on the README.md shows only one window and it may cause confusion. Also, I think it would be nice only one window when running the game in a low resolution screen.

Thank you for the game :)
