### ISSUE TITLE
Errors when opening with Vi IMproved 7.4

### ISSUE THREAD

**Issue by daniagudelos** [johngrib/vim-game-code-break#23]
Hi johngrib, 

I am getting the following errors when opening vim-game-code-break with Vi IMproved 7.4:

No matching autocommands                                                                                                                                
Error detected while processing function VimGameCodeBreak#game#main[2]..VimGameCodeBreak#common#new:
line    4:                                                                      
E117: Unknown function: funcref                                                 
E15: Invalid expression: funcref('<SID>rand')                                   
line    5:                                                                      
E117: Unknown function: funcref                                                 
E15: Invalid expression: funcref('<SID>drawChar')                               
line    6:                                                                      
E117: Unknown function: funcref                                                 
 E15: Invalid expression: funcref('<SID>getCharValue')                           
 line    7:                                                                      
 E117: Unknown function: funcref                                                 
 E15: Invalid expression: funcref('<SID>removeWord')                             
 line    8:                                                                      
 E117: Unknown function: funcref                                                 
 E15: Invalid expression: funcref('<SID>sleep')                                  
 line    9:                                                                      
 E117: Unknown function: funcref                                                 
 E15: Invalid expression: funcref('<SID>prepareLine')                            
 No matching autocommands                                                        

I'd appreciate if you could you provide a solution to this issue.

**Comment by johngrib** [comment]
Hello. VimGameCodeBreak requires Vim 8.0 or later.
Because I used `funcref` added in Vim 8.0.
Thank you.

**Comment by daniagudelos** [comment]
I upgraded my vim version and it works perfectly. Thank you.
