### ISSUE TITLE
Statusbar automatically sets to 2

### ISSUE THREAD

**Issue by ghost** [johngrib/vim-game-code-break#24]
I set the statusbar to 0 to don't see the statusbar but after running :VimGameCodeBreak command it makes statusline set to 2, Is there a solution?

**Comment by blueyed** [comment]
I guess it could be restored afterwards maybe?

**Comment by ghost** [comment]
I wrote the description. wrong, status bar was 0 it sets to 2. BTW it should be solved.

**Comment by johngrib** [comment]
@midnio Thank you for reporting this issue.

https://github.com/johngrib/vim-game-code-break/commit/51ef5fadc79e2af65b76d120093a4176dcdbca53
